### ISSUE TITLE
PostBuild error code -532462766 after 2.1.8 update

### ISSUE THREAD

**Issue by Kimmova** [turquoiseowl/i18n#307] opened 2016-11-10 12:51 UTC
Hi,

First of all I would like to say great job on this package, it is very intuitive and works really well for my ASP MVC 5 project after configuration.
I recently decided to run through NuGet package updates to get my project up to date.
One of these packages was your new version v2.1.8, and I was previously running v.2.1.7 without any issues.
However after updating the project refuse to build with this error message (my path replaced with "..."):
"The command ""C:\...\bin\i18n.PostBuild.exe" "C:\...\web.config"" exited with code -532462766."

Any idea what could have caused this? As far as I can tell one of the only differences (apart from the plugin packages themselves) is in my web.config file where this was added:
`<dependentAssembly>
        <assemblyIdentity name="i18n.Domain" publicKeyToken="b54a7283d4bad1bb" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-2.1.8.0" newVersion="2.1.8.0" />
      </dependentAssembly>`

Trying to comment this out however proved to make no difference. For now I have simply jumped back to v.2.1.7 since I have not experienced any problems or missing features for my use here.
But my OCD wants to update to newest version :) 

So I am in no rush, but if you have some spare time maybe you can let me know if you have any ideas for what might have caused this, or if you need more info from me let me know.

Have a good day!

**Comment by turquoiseowl** [comment] 2016-11-10 13:51
Pleased to hear the i18n library is helping you out.

This is the first time I've heard of this error. The negative error code would seem to equate to 0xE0434352 and googling comes up with some suggestions as to the cause. Would you be able to follow them up and get back to us here?

Alternatively running PostBuild.exe under the debugger may help diagnose what's going on...

**Comment by turquoiseowl** [comment] 2016-11-10 13:54
Just another thought: Have you tried running PostBuild.exe against a completely fresh ```locale``` folder hierarchy, say with just a single empty langtag sub folder?

**Comment by Kimmova** [comment] 2016-11-10 14:04
Tried running it as debug, and I got this error message:
Unhandled Exception: System.IO.FileLoadException: Could not load file or assembly 'i18n.Domain, Version=2.1.7.0, Culture=neutral, PublicKeyToken=b54a7283d4bad1bb' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at i18n.PostBuild.Program.Main(String[] args)

**Comment by Kimmova** [comment] 2016-11-10 14:09
Trying to empty the locales folder and rebuilding results in the i18n.PostBuild.exe file not occurring in my bin folder anymore. Also gives error code 9009 which I assume refers to the fact that the file is no longer present.

**Comment by turquoiseowl** [comment] 2016-11-25 14:39
Can we close this issue? Thanks.

**Comment by Kimmova** [comment] 2016-11-25 14:52
Sure, I am still running on version 2.1.7 since this is working for me. I just wanted to know if there was something simple I overlooked regarding this issue. But if this is a very rare case, then go ahead and close it :)

**Comment by turquoiseowl** [comment] 2016-11-25 15:11
Perhaps the latest version just published will help. Closing for now...

**Closed by turquoiseowl** 2016-11-25 15:11 UTC
