### ISSUE TITLE
Memory leaks

### ISSUE THREAD

**Issue by tomasr78** [turquoiseowl/i18n#391] opened 2019-10-11 15:06 UTC
Recently our web application started to throw out of memory and crashing IIS app pool. While investigating we have found that the cause of high memory usage is i18n. It generates about 500K of strings in our case which then moved to Large Objects Head, the LOH becomes extremely large and eventually, we get the app tool crash. The stack trace of the problematic methods is below. Is this known issue or somehow related to our app?

![image](https://user-images.githubusercontent.com/2582291/66662432-7c188a80-ec51-11e9-88dd-f02edf257981.png)

p.s. we using the latest version 2.1.15. We could share the dump file if needed.

**Comment by turquoiseowl** [comment] 2019-10-15 10:30
Hmm, first I've heard of this.

I've just done a quick review and it looks like TranslationItem.References collection is only appended to during PostBuild. Is the site static or are you doing on-the-fly updates to the content?

Further, is 500K necessarily that many strings? How big is the site? How much RAM does that translate to? WHat does the string count start at? How long does it take to grow to 500K?

**Comment by vhatuncev** [comment] 2020-04-10 22:00
@tomasr78 just wondering, did you solve the issue? How do you think it's possible to reproduce this issue? I think to create a page with 500K records to translate and see the memory state.

**Comment by turquoiseowl** [comment] 2020-11-16 21:11
Closing for now. Please re-open if still an issue.

**Closed by turquoiseowl** 2020-11-16 21:11 UTC
