### ISSUE TITLE
Texts with ampersands cannot be localized

### ISSUE THREAD

**Issue by zingix** [turquoiseowl/i18n#355] opened 2017-10-03 13:07 UTC
I have to following text localized in my PO file.

`Qualität &amp; Quantität`

The text is requested by the web page using HTTP GET and returned by the web server using JSON. When I dig into the code, I can see that the lookup in the concurrent dictionary is with the following string:

`Qualität \u0026amp; Quantität`

This is also true for other special HTML characters like &copy;

**Comment by turquoiseowl** [comment] 2017-10-03 13:50
I've just done a quick test here adding your message string to an HTML file and all works as expected.

Did you say the source file is a .json file? If so I'm not clear what the correct behaviour should be and that it is not what you are experiencing (?) given that ```&amp;``` is an HTML thing.

**Comment by zingix** [comment] 2017-10-03 14:05
I think the error comes from a combination of the JSON response and the localization. The response header looks like this:

```
Cache-Control:private
Content-Length:1376
Content-Type:application/json; charset=utf-8
```

Whereas the response itself is the following:

```
[ {
		"Text": "Qualität \u0026amp; Quantität",
		"Id": 1000919
	}, {
		"Text": "Self-organisation",
		"Id": 1000914
	}
]
```

I think the ASP.Net JSON encoding converts the `&amp;` to `\u0026amp;` and because the request handler kicks in after the encoding, the value cannot be looked up.

**Comment by turquoiseowl** [comment] 2017-10-03 14:37
The following comes up as valid JSON using jsonlint.com:

```
{
	"Text": "Qualität &amp; Quantität"
}
```

Not wanting to pass the buck but it looks to me like the problem is with ASP.NET's handling of JSON. How is i18n supposed to know you don't actually want ```\u0026amp;``` in the response?

**Comment by zingix** [comment] 2017-10-03 15:54
You are right, i18n has no way of knowing what you want. But when the JSON standard defines that an ampersand can also be represented by \u0026 then this should be handled correctly when looking up the values from the dictionary.

I created a pull request that fixes the issue. What do you think? #356

**Comment by turquoiseowl** [comment] 2018-07-02 15:47
Closing for now. Please re-open is appropriate. Thanks.

**Closed by turquoiseowl** 2018-07-02 15:47 UTC
